FROM python:3.10-slim

WORKDIR /app

# install dependency system
RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# upgrade pip
RUN pip install --upgrade pip

# install insightface and required runtime deps
RUN pip install insightface onnxruntime opencv-python-headless numpy scikit-image

# test import
# RUN python -c "import insightface; print('InsightFace installed')"

CMD ["python"]